[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则


;设置规则标志位
ruleset=Ⓜ️ 联通服务,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/liantonwifi.list
ruleset=Ⓜ️ 移动服务,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/yidongwifi1.list
ruleset=Ⓜ️ 土耳其服务1,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/tuerqiwifi1.list
ruleset=Ⓜ️ 土耳其服务2,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/tuerqiwifi2.list
ruleset=Ⓜ️ 南非服务1,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/nanfeiwifi1.list
ruleset=Ⓜ️ 南非服务2,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/nanfeiwifi2.list
ruleset=Ⓜ️ 巴基斯坦服务01,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan01.list
ruleset=Ⓜ️ 巴基斯坦服务02,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan02.list
ruleset=Ⓜ️ 巴基斯坦服务03,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan03.list
ruleset=Ⓜ️ 巴基斯坦服务04,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan04.list
ruleset=Ⓜ️ 巴基斯坦服务05,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan05.list
ruleset=Ⓜ️ 巴基斯坦服务06,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan06.list
ruleset=Ⓜ️ 巴基斯坦服务07,https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/bajisitan07.list
ruleset=🐟 漏网之鱼,[]FINAL







;WIFI位置
custom_proxy_group=Ⓜ️ 移动服务`select`[]移动
custom_proxy_group=Ⓜ️ 联通服务`select`[]联通
custom_proxy_group=Ⓜ️ 土耳其服务1`select`[]土耳其01
custom_proxy_group=Ⓜ️ 土耳其服务2`select`[]土耳其02
custom_proxy_group=Ⓜ️ 南非服务1`select`[]南非01
custom_proxy_group=Ⓜ️ 南非服务2`select`[]南非02
custom_proxy_group=Ⓜ️ 巴基斯坦服务01`select`[]巴基斯坦fallback01
custom_proxy_group=Ⓜ️ 巴基斯坦服务02`select`[]巴基斯坦fallback02
custom_proxy_group=Ⓜ️ 巴基斯坦服务03`select`[]巴基斯坦fallback03
custom_proxy_group=Ⓜ️ 巴基斯坦服务04`select`[]巴基斯坦fallback04
custom_proxy_group=Ⓜ️ 巴基斯坦服务05`select`[]巴基斯坦fallback05
custom_proxy_group=Ⓜ️ 巴基斯坦服务06`select`[]巴基斯坦fallback06
custom_proxy_group=Ⓜ️ 巴基斯坦服务07`select`[]巴基斯坦fallback07
custom_proxy_group=🐟 漏网之鱼`select`.*[]DIRECT




;节点选择位置


custom_proxy_group=联通`fallback`(联通)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=移动`fallback`(移动)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=土耳其01`fallback`(土耳其01|土耳其03)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=土耳其02`fallback`(土耳其02|土耳其04)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=南非01`fallback`(南非01|南非02)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=南非02`fallback`(南非02|南非01)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback01`fallback`(巴基斯坦01|巴基斯坦02)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback02`fallback`(巴基斯坦02|巴基斯坦01)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback03`fallback`(巴基斯坦03|巴基斯坦04)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback04`fallback`(巴基斯坦04|巴基斯坦03)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback05`fallback`(巴基斯坦05|巴基斯坦06)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback06`fallback`(巴基斯坦06|巴基斯坦05)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=巴基斯坦fallback07`fallback`(巴基斯坦07|巴基斯坦06)`http://www.gstatic.com/generate_204`300,,50




;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/daosheng1991/peizhi/refs/heads/main/clash-rule-tongyong.yaml



;luck